name: ADORe CLI CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  x86_64:
    name: Native x86_64
    uses: ./.github/workflows/reuse-build.yaml
    with:
      platform: 'ubuntu-latest'
      archive_name: 'logs-x86'
    secrets: inherit

  arm64:
    name: Native ARM64
    uses: ./.github/workflows/reuse-build.yaml
    with:
      platform: 'ubuntu-24.04-arm'
      archive_name: 'logs-arm64'
    secrets: inherit
